# Generated by Django 4.2.2 on 2023-06-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='avions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('compagnie', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
            ],
        ),
    ]
