# Generated by Django 4.2.2 on 2023-06-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compagnies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='compagnies',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('paysderatachement', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='avions',
        ),
    ]
