# Generated by Django 4.2.2 on 2023-06-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pistes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=100)),
                ('longueur', models.CharField(max_length=100)),
                ('aeroport', models.CharField(max_length=100)),
            ],
        ),
    ]
