# Generated by Django 4.2.2 on 2023-06-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='typeavions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('marque', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('modele', models.CharField(max_length=100)),
                ('longueur_piste', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images_upload/')),
            ],
        ),
    ]
